### PR TITLE
Fix selecting payload blocks

### LINKED ISSUE #48: Modify hexy's html support to output hex and ascii two separate columns
We use [hexy](https://github.com/a2800276/hexy.js) to display the payload as hex and ASCII, but if you want to mark and copy multiple lines of the ascii you end up also copying hex. Modify hexy so the HTML output has the hex and ASCII in two separate columns instead of line by line.

### PR DESCRIPTION
**Pull request by dkumiszhan**
Fixes #48

### CODE REVIEW

File: src/components/Content.svelte [hunk 1]
```diff
@@ -40,4 +67,18 @@
...
     }
+
+    .pre {
+        display: flex;
+        white-space: pre;
+        justify-content: flex-start;
+        gap: 20px;
+        font-family: monospace;
+        padding-top: 15px;
+        padding-bottom: 15px;
```
Comment (glaslos) [inline src/components/Content.svelte:78]: FYI I added some padding top and bottom of the payload
